### ISSUE TITLE
Original Script Origins?

### ISSUE THREAD

**Issue by huttsMichael** [Bercik1337/rt-auto-install#16]
Hi, it's mentioned in the description that you took over the script from someone else. I believe I have that original version installed and am having trouble tracking down where exactly I got it from. Would anyone be able to link to the original script/author? I'm trying to figure out something related to it. Thanks!

**Comment by huttsMichael** [comment]
Nevermind, finally found it. https://github.com/arakasi72/rtinst

**Comment by Bercik1337** [comment]
@huttsMichael hey, i just noticed your post. Well it's incorrect, author was named Patrick Kerwood which is even mentioned in earler versions of my script (before 0.3). I have never seen rtinst by arakasi before.
