### ISSUE TITLE
SCGI package not available for ARM systems

### ISSUE THREAD

**Issue by MikeShiner** [Bercik1337/rt-auto-install#17]
Firstly, thanks for putting this together, looks great.

Currently running Ubuntu Server 20.04 LTS on my Raspberry Pi 4.

Script correctly identifies my system, but the SCGI package it manually installs is hardcoded to AMD arch.
I have a quick check on the server, and only AMD and i386 are available.

Do you know of an alternative for ARM based systems?

**Comment by Bercik1337** [comment]
@MikeShiner 
Hey
I don't have access to RPI4 hardware, so I can't test if it will work, but try swapping link on line 495 to http://ftp.debian.org/debian/pool/main/s/scgi/libapache2-mod-scgi_1.13-1.1_arm64.deb

I doublechecked that RPI4 uses arm64, but ARMs are confusing to me, there are also other versions:
armel and armhf -> https://packages.debian.org/buster/libapache2-mod-scgi

But hopefully this arm64 will do.
Let me know if that works.

**Comment by Bercik1337** [comment]
It's line 502 now (recently updated). Look for function INSTALL_SCGI

**Comment by caseybekey** [comment]
So, just wanted to add to it that http://mirrors.edge.kernel.org/ubuntu/pool/universe/s/scgi/ has i386.deb as well. so changing that worked for me.
So that could be a possible change in the script.

**Comment by Bercik1337** [comment]
@caseybekey hey, thx for info, any chance you could prepare the code and push it? i'll see and accept
just please remember to add some kind of check step to verify if we're x86_64 or i386. because by default it assumes 64 bit

thanks!

**Comment by Whoffie** [comment]
> @MikeShiner Hey I don't have access to RPI4 hardware, so I can't test if it will work, but try swapping link on line 495 to http://ftp.debian.org/debian/pool/main/s/scgi/libapache2-mod-scgi_1.13-1.1_arm64.deb

Can confirm this works for my RPI4 on Ubuntu 22.04, will this be implemented into the script?

**Comment by Bercik1337** [comment]
> > @MikeShiner Hey I don't have access to RPI4 hardware, so I can't test if it will work, but try swapping link on line 495 to http://ftp.debian.org/debian/pool/main/s/scgi/libapache2-mod-scgi_1.13-1.1_arm64.deb
> 
> Can confirm this works for my RPI4 on Ubuntu 22.04, will this be implemented into the script?

thanks for input buddy, i'll try to update this this/next weekend
as you can see, i lack free time, but if it works then I trust you and just update code. I have nowhere to run it.

**Comment by Bercik1337** [comment]
@Whoffie good news and bad news:
Good is i just pushed commit
Bad is i also rolled it back

It's actually little more complex than I thought.  With Raspbian it's easy, because it's only for raspberry, but I'd need another function for Ubuntu/Debian to check if it's ARM or x86 system.
In theory I could do it without hardware, but it's like blindfolded surgery. 

Until I get my hands on Rpi (or remote hands of someone who's very patient) I won't be risking breaking the script because this needs to be tested well.

So to summarize:
for now, manual change of this URL will do, when I'll get Rpi, then we can try to fix it in a proper way.

**Comment by myloginforgithub** [comment]
It's not working on armhf, dude

**Comment by Whoffie** [comment]
I can’t speak for armhf, Raspberry Pi 4 uses arm64.

**Comment by Bercik1337** [comment]
@myloginforgithub and @Whoffie  i think i got an idea on how to solve the problem (make it automatic)
But you must participate: please paste  `/etc/os-release` and `lscpu` here. I don't have modern Raspberry pi hardware so I need your setup. This should be enough to "simulate" other platform.

**Comment by myloginforgithub** [comment]
@Bercik1337
os-release:
`PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`
and lscpu:
`Architecture:                    armv7l
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           5
Model name:                      Cortex-A7
Stepping:                        r0p5
CPU max MHz:                     1368,0000
CPU min MHz:                     480,0000
BogoMIPS:                        30.85
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm`

**Comment by Bercik1337** [comment]
@myloginforgithub sorry for my silly question but I'm not good with ARMs - is armv71 the same as armhf? or these are two different architectures?

**Comment by myloginforgithub** [comment]
@Bercik1337, i don't know too. But this is output of requested commands. During installation of SCGI package was error about  "armhf". Where i can found logs with that?
I'm already use `rtinst` instead of your script.

**Comment by Bercik1337** [comment]
If i'm lucky I'll fix it this weekend. But to be REALLY sure if it works. Some of you need to run it - as i still don't have modern Raspberry pi.
Gonna update this thread when it's done.

**Comment by Whoffie** [comment]
> @myloginforgithub sorry for my silly question but I'm not good with ARMs - is armv71 the same as armhf? or these are two different architectures?

They look to be the same per this link

https://stackoverflow.com/questions/37790029/what-is-difference-between-arm64-and-armhf

**Comment by ballonnetje** [comment]
for anyone with an rb pi and having this problem;

Like they said before just replace the link (around line 502, not exactly 502) with the ARM version URL found here under Download > Binary (https://debian.pkgs.org/10/debian-main-arm64/libapache2-mod-scgi_1.13-1.1_arm64.deb.html) 

Then everything works :)

**Comment by ballonnetje** [comment]
Oh BTW, after installation completes the command line stays red.

**Comment by Bercik1337** [comment]
@ballonnetje yes, script is evolving so line number is changing.
I still don't have any available rpi on my hands. So much so I switched to Dell WYSE platform because of that. Perhaps I'll exclude Pi support with next update as some people can't handle this exception.

**Comment by ballonnetje** [comment]
Tbh this was a quick fix and no need for any stress - at least for me. If it's too much of a hastle to implement the change by all means just don't do it.  :)

Btw I don't see why you need a rpi for this right now, but that could be my noob view;
You only need a check which system it is > arm or other. Then get the correct link for the system. 
The rest of the installer worked without any problem on my pi.

**Comment by Bercik1337** [comment]
it's not that easy, there different architectures of Pi (different CPU arch). That means you can't use the same deb package for all of them. What works for you above, won't work in early versions of Pi. :(

**Comment by rjalexa** [comment]
For anyone looking at this as of Jan 2024:
line to correct is currently 530
replace with package https://debian.pkgs.org/10/debian-main-arm64/libapache2-mod-scgi_1.13-1.1_arm64.deb.html
```
I have a raspberry 4 model B

bob@rutorrent:~/rt-auto-install $ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
bob@rutorrent:~/rt-auto-install $ lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Cortex-A72
    Model:               3
```

**Comment by Bercik1337** [comment]
I'll try to refresh whatever I can, but i'm chronically out of time :(

**Comment by rjalexa** [comment]
Ouch sorry that package does not exist anymore :(
this seems to work though
`http://ftp.de.debian.org/debian/pool/main/s/scgi/libapache2-mod-scgi_1.13-1.1_arm64.deb`

**Comment by Denkai01** [comment]
> it's not that easy, there different architectures of Pi (different CPU arch). That means you can't use the same deb package for all of them. What works for you above, won't work in early versions of Pi. :(

since this is old but may still be relevant, armv71 and armhf are the same thing, 32 bit arm. armv71 was the name they used on Pi's 1 and 2 before it it needed to seperate arch types.  for the most part, like with most 32 bit systems, armhf is pointless.
