### ISSUE TITLE
cloudflare: Plugin will not work. Webserver user can't access external program (python)

### ISSUE THREAD

**Issue by pemaaaw** [Bercik1337/rt-auto-install#18]

**Comment by Bercik1337** [comment]
You can remove plugin, it's not necessary. Both cloudflare and the other one for screenshot.

**Comment by pemaaaw** [comment]
@Bercik1337 thanks for the reply but i need the screenshot plugin, i already do chmod 777 /var/www/rutorrent also restarting tmux session but nothing change, i still got an error plugin.

**Comment by Bercik1337** [comment]
@pemaaaw 
apt install ffmpeg

**Comment by pemaaaw** [comment]
thanks @Bercik1337

**Comment by Bercik1337** [comment]
done
