### ISSUE TITLE
wget is used inside script

### ISSUE THREAD

**Issue by ouzo12** [Bercik1337/rt-auto-install#19]
I only saw this beacuse i installed the script into a lxc container with out the wget installed.

wget is used inside script but not included as an dependency like curl in the script.

apt-get -y install apache2-utils unzip curl
should be 
apt-get -y install apache2-utils unzip curl wget

so this lines will work.
wget http://mirrors.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb
wget http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb

**Comment by Bercik1337** [comment]
Hey,
hm first time i see system without without wget, but fine - i'll add it just anyone else has the same problem. Nearest commit
