### ISSUE TITLE
Some dependecies are missing - WAD?

### ISSUE THREAD

**Issue by g0r3** [Bercik1337/rt-auto-install#20]
Hi,

I used your install script on Ubuntu 20.04 and it worked out great. But what I noticed is that it does not install all the dependencies rutorrent seems to expect. I manually had to install `ffmpeg` and `sox`. And the one thing I cannot get resolved is the rutorrent UI complaining about `cloudflare plugin: cloudscraper module can't be loaded in Python.` No matter where and how I installed the python cloudscraper package, rutorrent would not pick it up. So I was wondering, if those missing dependecies are WAD.

**Comment by g0r3** [comment]
Hi,
i got everything working but the cloudflare plugin. It just does not pick up the python package. Also importing the package manually in the python interpreter does not work (but which is not your concern). I ended up just deleting the plugin since I don't seem to need it. Thanks for your help.

**Comment by Bercik1337** [comment]
No problemo. Enjoy
