### ISSUE TITLE
Failed to start rtorrent-init.service: Unit rtorrent-init.service not found.

### ISSUE THREAD

**Issue by xxtensazenxx** [Bercik1337/rt-auto-install#21]
Just did a fresh install and the .service file is not working. When I try to run service rtorrent-init start is errors out with "Failed to start rtorrent-init.service: Unit rtorrent-init.service not found."

**Comment by Bercik1337** [comment]
what system? distro name and version
please also give full log from installation, maybe there's an error message somewhere there

if possible reinstall OS and restart the script to gather all this data

**Comment by Bercik1337** [comment]
@xxtensazenxx please respond or i'll close the issue in let's say 2 days

**Comment by Bercik1337** [comment]
No response. Closing.

**Comment by Impact009** [comment]
I have the same issue on Debian 12 (Bookworm) (64bits). I've reformatted and performed a clean installation three times. Where is the log from the installation? I didn't see a relevant log within the script's code.
