### ISSUE TITLE
uninstall script

### ISSUE THREAD

**Issue by ceadd** [Bercik1337/rt-auto-install#22]
hi
script worked great, thank you but i need to reverse it and remove rutorrent. 
hopefully this isnt a dumb question but i tried manually removing a few packages found in the script and rtorrent kept on running. anyways i can get some advice on how to remove this?

**Comment by Bercik1337** [comment]
yes, all you have to do is remove all packages installed by script and manually delete "rutorrent" itself (it's in /var/www/rutorrent) 
remember to STOP all services before you proceed (apache2, rtorrent) because Linux allows uninstalling stuff while you run it .

Tell me if it helped.

**Comment by Bercik1337** [comment]
@ceadd any update?

**Comment by Bercik1337** [comment]
No response. Closing.
