### ISSUE TITLE
Plugins not dowloading

### ISSUE THREAD

**Issue by iammike2** [Bercik1337/rt-auto-install#24]
From the following function

```
# Function for the Plugins download part.
function DOWNLOAD_PLUGIN {
		curl -L "http://dl.bintray.com/novik65/generic/plugins-3.6.tar.gz" -o plugins-3.6.tar.gz


```

Getting a 502 Bad Gateway on download!!

**Comment by Bercik1337** [comment]
Hey, they disabled site. Let me take care of this. Hopefully i have those plugins offline somewhere.

**Comment by Bercik1337** [comment]
Fixed version coming right up! it's self hosted so @iammike2  it should never go down again
