### ISSUE TITLE
Installation dies on Hetzner servers with IPv6

### ISSUE THREAD

**Issue by MorphyDK** [Bercik1337/rt-auto-install#26]
--2022-05-31 11:24:27--  http://mirrors.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb
Resolving mirrors.kernel.org (mirrors.kernel.org)... 2604:1380:45e3:2400::1, 139.178.88.99
Connecting to mirrors.kernel.org (mirrors.kernel.org)|2604:1380:45e3:2400::1|:80... 

Dont complete the installation.

**Comment by Bercik1337** [comment]
@MorphyDK any chance this server is non-amd64? Like arm or something>

**Comment by MorphyDK** [comment]
Hmm good question @Bercik1337 

Its cloudbased VPS .. I typically use them to test out systems ( which Havent been an problem before :) )

**Comment by Bercik1337** [comment]
Paste me the
`uname -a`

**Comment by MorphyDK** [comment]
Linux ubuntu-2gb-hel1-1 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Bercik1337** [comment]
Try to manually get this file from CLI
`wget http://mirrors.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb`

Also what error did you get during installation? You pasted what it's about to do (download the file) but not what was the actual error.

**Comment by MorphyDK** [comment]
Well it show me to another site ( redirected ) but none of the sites actually started to download.  :/

**Comment by MorphyDK** [comment]
--2022-05-31 14:29:37--  http://mirrors.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.de
Resolving mirrors.kernel.org (mirrors.kernel.org)... 139.178.88.99, 2604:1380:45e3:2400::1
Connecting to mirrors.kernel.org (mirrors.kernel.org)|139.178.88.99|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://mirrors.edge.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.de [following]
--2022-05-31 14:29:38--  http://mirrors.edge.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.de
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 147.75.101.1, 2604:1380:2001:3900::1
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|147.75.101.1|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-05-31 14:29:38 ERROR 404: Not Found.

**Comment by MorphyDK** [comment]
Just tried on another server - hmm works fine on my local ubuntu server.. Kinda odd!

**Comment by Bercik1337** [comment]
Maybe they (hetzner) is blocking or doing something on purpose. I just downloaded this deb file without any problem on my computer.
You can manually upload this file (SCP) and install it with dpkg. Comment out lines in script for installation and that's it.
BUT
I assume you don't know how to proceed, but I won't be able to help without even access to some this system. Also hetzner is not the best place for seedbox in my option, there are dedicated places where you can buy them.

I also noticed you just pasted output, as expected - they forwarded the request to other host for some reason where this file is not placed. It's "their" fault.

**Comment by Bercik1337** [comment]
> Just tried on another server - hmm works fine on my local ubuntu server.. Kinda odd!

It's not odd, it's hetzner fault for this mumbo-jumbo redirect. Not mine.

**Comment by MorphyDK** [comment]
Nothing downloaded

Info

 wget --max-redirect=0 http://mirrors.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb
--2022-05-31 14:34:31--  http://mirrors.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb
Resolving mirrors.kernel.org (mirrors.kernel.org)... 139.178.88.99, 2604:1380:45e3:2400::1
Connecting to mirrors.kernel.org (mirrors.kernel.org)|139.178.88.99|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://mirrors.edge.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb [following]
0 redirections exceeded.

**Comment by Bercik1337** [comment]
Ok, so as you can see, it desepratly wants to redirect you for some weird reason.
Option A) pick another cloud solution, or local one.
Option B) follow instruction for manual installation of .deb package - but there's a chance if there's a problem with this package, there might be another error in 3min for something else.

Note do self, don't use Hetzner.

**Comment by Bercik1337** [comment]
but the entire script, works locally?

**Comment by Bercik1337** [comment]
Then spin up a new VM, or livecd. I can asure you it works.

Remember, VPS uses templates that are not fresh installs. Also they may be doing weird stuff, like blocking, redirects (as above) and much more.

**Comment by MorphyDK** [comment]
Cheers @Bercik1337 

Trying a fresh spin up later :) - thanks for your fast replies.

**Comment by Bercik1337** [comment]
> Cheers @Bercik1337
> 
> Trying a fresh spin up later :) - thanks for your fast replies.

any news?

**Comment by MorphyDK** [comment]
Sorry no. Work ;)
