### ISSUE TITLE
How to stop/restart/update/upgrade rutorrent?

### ISSUE THREAD

**Issue by MorphyDK** [Bercik1337/rt-auto-install#29]
Hi Bercik1337

How to we start/stop/restart/update/upgrade manually?

Is it me or am I missing the info ? :)

Which ini files loads the plugins? 

/var/www/rutorrent/conf/plugins.ini is empty , but all plugins are loaded .

Would be great to have an update function like this one https://github.com/arakasi72/rtinst

**Comment by Bercik1337** [comment]
@MorphyDK  rutorrent it's just a zip file of php and some other website related files. You can get new version and unpack it into /var/www/rutorrent
that's it, no hardcore configuration needed

**Comment by MorphyDK** [comment]
@Bercik1337 how to start/stop it ? :)

**Comment by Bercik1337** [comment]
You only care about rtorrent service. rutorrent is under apache2

systemctl stop rtorrent
systemctl stop apache2
and so on

**Comment by MorphyDK** [comment]
Cheers :)

Thanks for the fast reply
