### ISSUE TITLE
Feature Details

### ISSUE THREAD

**Issue by Lucif3r-MorningSter** [Bercik1337/rt-auto-install#3]
Hi:
* Does this script support multi user?
* Does it have option for setting disk quota?

**Comment by Bercik1337** [comment]
@Lucif3r-MorningSter sorry for delay. Didn't get email about opened issue.
 
> Does this script support multi user? 

Not in wizard way, but you can always add other users post installation with htpasswd.
    

> Does it have option for setting disk quota?

Also no, I spent some time to make it as easy to use as possible, quotas are used only on multi-user seedbox. So by default if someone does that - they know what they are doing.  Maybe in future I'll do that, but so far there are many other features to be done and I already have so little time ;(  Didn't even fix centos support yet.

If you have any other questions - hit me.
