### ISSUE TITLE
Feature request: deploy using HTTPS

### ISSUE THREAD

**Issue by tbennett6421** [Bercik1337/rt-auto-install#31]
I will see if I can add a PR to add the functionality, but anyone using a seedbox not locally should be accessing rutorrent over TLS in order to avoid traffic snooping to sniff the credentials.

**Comment by tbennett6421** [comment]
I added #32. I don't know the best way to handle this, but I highly recommend asking the user if they wish to set a servername for apache. Then if so, you collect the servername.

This will allow you to use the server name later in the vhost configuration, and if you choose to add lets-encrypt support. I just added the servername to my local copy.

**Comment by tbennett6421** [comment]
I would also recommend you disable port 80, or redirect automatically to 443. We really don't want people to be using plain-text comms for internet hosts. Just my 2cents.

**Comment by tbennett6421** [comment]
For reference, my config
```
<VirtualHost *:80>
  ServerName rex.example.com
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/rutorrent
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    Redirect / https://rex.example.com/

    CustomLog /var/log/apache2/rutorrent.log vhost_combined
    ErrorLog /var/log/apache2/rutorrent_error.log
    SCGIMount /rutorrent/RPC2 127.0.0.1:5000

    <Directory "/var/www/rutorrent">
        AuthName "Tits or GTFO"
        AuthType Basic
        Require valid-user
        AuthUserFile /var/www/rutorrent/.htpasswd
    </Directory>
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
  DocumentRoot /var/www/rutorrent
  ServerName rex.example.com

  LogLevel info ssl:warn
  ErrorLog /var/log/apache2/ssl_error.log
  CustomLog /var/log/apache2/ssl_access.log common

  <Directory "/var/www/rutorrent">
      AuthName "Tits or GTFO"
      AuthType Basic
      Require valid-user
      AuthUserFile /var/www/rutorrent/.htpasswd
  </Directory>

SSLEngine on
SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key
</VirtualHost>
</IfModule>
```

**Comment by Bercik1337** [comment]
@tbennett6421 thanks buddy for input. I'll take a look at it ASAP, it's jut this will be in weeks time (superbusy).
SSL is something I had on my TODO for quite some time (actually you can see it in TODO :sweat_smile:  )

Just out of curiosity, any change you'd manage to create another PR for Let's Encrypt instead of self-signed?

**Comment by tbennett6421** [comment]
If I have time I will, I will probably be working on converting this to an ansible-playbook as most of the ansible playbooks on the internet are not actively being supported.

I'm far better with ansible then just with straight bash, and it makes idempotency fairly easy.

**Comment by Bercik1337** [comment]
Done, merged it, but i made small changes
1. Bring back original DocumentRoot
2. Changed age of cert
3. Made it automatically reply cert config question (noobs would got confused, and it wouldn't be automatic no more)

Always in a hurry, so I tested it only on a single system (Mint) but it should be fine for all :crossed_fingers: 

Thanks for your input.
