### ISSUE TITLE
Begin Installation fails

### ISSUE THREAD

**Issue by ballonnetje** [Bercik1337/rt-auto-install#37]
Hi,

Now just earlier today I installed with only one issue; the AMD package instead of ARM package which is known.

But due to circumstances I re-installed ubuntu server on my pi and also tried to re-install this software.

It immediately errors out: 

```
>> 0
ln: failed to create symbolic link '/etc/apache2/mods-enabled/scgi.load': No such file or directory
Creating apache vhost
./Rt-Install-minimal: line 616: /var/www/rutorrent/.htpasswd: No such file or directory
```

after this it just jumps to the end screen as if it is completed but nothing is running and files are not created. 

What is happening here? what am I doing wrong?

**Comment by ballonnetje** [comment]
It also does not display versions of the softwares:
`
 Script last modified:  2022/10/15
     rTorrent version:
   libTorrent version:
    ruTorrent version:
       script version:  1.7
`

**Comment by Bercik1337** [comment]
Paste the
`/etc/os-relase`
and
`uname -a`

FYI: I will remove support for Raspberry soon. It's difficult to develop something if I don't have a platform to test it.

**Comment by Bercik1337** [comment]
@ballonnetje ping

**Comment by ballonnetje** [comment]
Sorry for not replying.

I installed 22.10 when it went wrong and it worked  with 22.04. 
I came to this conclusion as nothing else could have been it since nothing really changed.

**Comment by Bercik1337** [comment]
22.10 is not yet on supported OS list (visible on main page). I didn't have time to do it yet.
So this is why it didn't work.

**Comment by Bercik1337** [comment]
But i found that Ubuntu section misses info about not supported release. I must've deleted it at some point.
This will be done soon.
