### ISSUE TITLE
Questions about update (not issue)

### ISSUE THREAD

**Issue by Miedzcu** [Bercik1337/rt-auto-install#39]
Questions from a total amateur not actively using linux wanting to jump from version 1.6 of the script to 1.7 (i only know how to install linux and how to install this script, I don't know anything about upgrading without losing data, and I dont made any attempt yet, I want to know how theoretically to do it without hurting data/configuration):

Does updating the script require specific actions to preserve downloaded data and program/add-on settings? 
Is it enough to reinstall the latest script (using exactly the same steps as for installation)? 
Or is it all redundant because everything auto-updates?

**Comment by Bercik1337** [comment]
@Miedzcu Sam skrypt tylko instaluje rzeczy. W uproszczeniu nie ma znaczenia której jego wersji użyłeś. Tu masz changelog 1.6 vs 1.7 https://github.com/Bercik1337/rt-auto-install/commits/master/Rt-Install-minimal
Tak naprawdę jedną zmiana "dla kowalskiego" jest dodanie https - jeśli z tego nie korzystasz to nie ma nawet potrzeby nic zmieniać.

Skrypt służy tylko do instalacji - nie testowałem go podczas aktualizacji z starszej do nowszej wersji. W zwiazku z tym, nie zalecam aby to robić - zwłaszcza jeśli jesteś początkujący.

Innymi słowy, jeśli to co masz działą - to wersja 1.7 w niczym nie będzie lepsza.

Daj znać czy to wystarczy jako odpowiedź

**Comment by Miedzcu** [comment]
Wybacz za mój łamany angielski. 

To jest w pełni wystarczająca odpowiedź! :) aczkolwiek jest to HTTPS w komunikacji miedzy nami a klientem czy miedzy klientem a trackerem (SSL)? 

W drugim przypadku jak najbardziej korzystam dlatego od dłuższego czasu rozmyślam nad możliwościami aktualizacji zerkając w changelogale z racji dużej bazy danych przed tym krokiem chciałem poznać bezpieczny sposób by nie okazało się to katastrofą. 1.6 i HTTP też mi wystarczy! 

Mega robota Bercik! Gdyby nie tówj skrypt nie było by mnie na Linux i trackerach które wymagają rtorrent.

**Comment by Bercik1337** [comment]
@Miedzcu to jest https gui<-->user, z kolei to czy połączenie do trakera jest szyfrowane definuje sam plik .torrent czyli to co pobierasz ze strony z torrentami.

Jeśli chcesz zmienić tracker na szyfrowany - Najczęściej wystarczy wziąć  kliknąć prawym na pozycje w rutorrent przez przeglądarkę. Nastęnie edit torrent i tam powinieneś mieć URL trackera. Wystarczy dopisać "s" za http i jeśli tracker obsługuje to powinno już działać. Spróbuj na jednym najmniejszym/najmniej ważnym i zobacz czy będzie śmigać. Pamiętaj wpierw daną pozycje calkowicie zatrzymać [stop]
