### ISSUE TITLE
Bad response from server: 500 [error,getplugins]) Internal Server Error

### ISSUE THREAD

**Issue by terrorindeed** [Bercik1337/rt-auto-install#40]
Just ran sudo apt upgrade -y, restarted ubuntu VM, and getting this error.
Ubuntu 20.4.5 LTS

Thoughts?

**Comment by terrorindeed** [comment]
****FIXED****
Found a similiar post on reddit. https://www.reddit.com/r/seedboxes/comments/6hto0i/rutorrent_fix_bad_response_from_server_500/


I had to go into /var/www/rutorrent/share/users/<username>/settings/tasks and delete the most recently dated folder in there. Reloaded rutorrent and its alive

**Comment by terrorindeed** [comment]
New issue. After deleting the recent task, I thought I should delete the other tasks present. Mistake! 

I now cannot create a new torrent - Bad response from server: (500 [error,taskcheck])

**Comment by Bercik1337** [comment]
my tasks folder is empty, so this shouldn't be the reason for problem.
i'll setup a vm with 20.04 and test it out soon.

**Comment by Bercik1337** [comment]
@terrorindeed 
I installed 20.04, installed rutorrent, downloaded debian torrent. Did `apt upgrade -y` then reboot and added new torrent. All works fine.
Check if you rtorrent is even enabled with 
`sudo systemctl status rtorrent`

**Comment by terrorindeed** [comment]
Is there a way to reinstall rutorrent or you entire script. without losing data? Something is broken in my settings. When I was creating a new .torrent the other day, I got timeout request, which left a task in that folder. I created 3 more .torrent files and all was fine until the same thing happened. After which, rutorrent could not see rtorrent. I increased php.ini memory limit, that didnt help.
I found the above solution, and as soon as I deleted the most recent task in the folder, rutorrent connected back to rtorrent. I thought maybe I should delete the unfinished task, but whatever happened in that rm -r command, has broken my ability to create new .torrent files. I went so far as to delete the /tasks/ folder and reboot, rtorrent and rutorrent establish a connection, I am still seeding and I can add .torrent files, but as soon as I create a .torrent file, rutorrent breaks again.

**Comment by Bercik1337** [comment]
Yes you can save critical rutorrent data. All you need to do is `tar`  two locations:
`/var/www/rutorrent` and 
`~/.rtorrent-session`

these two places have all info on downloaded/uploaded stats, which torrents are in the queue etc

I'm afraid you might damage some files in there, and reinstalling script and restoring this folder could not help.

If possible, backup all your files from ~/Downloads reinstall system fresh. rerun script and add .torrents again. This will rehash all already downloaded files in ~/Downloads folder.

And please.. don't randomly delete some files without backup first, (or modify PHP settings).

**Comment by terrorindeed** [comment]
I will attempt a fresh install, this will be ugly.lol. I've got over 35TB on this VM.lol

**Comment by Bercik1337** [comment]
@terrorindeed any update?

**Comment by Bercik1337** [comment]
No info. Closing.
