### ISSUE TITLE
Installing ruTorrent 3.10 vs latest version 

### ISSUE THREAD

**Issue by PhantomEight** [Bercik1337/rt-auto-install#44]
I ran this last night on a new VM and it's still installing ruTorrent 3.10.   Am I missing a way to get this to install 4.x?

**Comment by Bercik1337** [comment]
@PhantomEight no, i simply didn't have time to update from 3.10 to something newer. Maybe this month I'll find the time.

**Comment by Bercik1337** [comment]
Done, updated to newest ruTorrent 4.1.6
