### ISSUE TITLE
RuTorrent Not Restarting

### ISSUE THREAD

**Issue by dgronos** [Bercik1337/rt-auto-install#45]
After reboot, Rtorrent or Rutorrent not restarting.  I have to run the script again to log in to Rutorrent?

**Comment by Bercik1337** [comment]
no, you shouldn't.
do you use it in docker or something?

**Comment by dgronos** [comment]
Actually, I haven’t figured it out other than it is not the script, but my Firefox.  Every other browser it works just fine.  Actually, it works fine in Private browsing in Firefox, but not the regular browser.  I will continue to troubleshoot.Thanks for the response and a cool script.

**Comment by Bercik1337** [comment]
Sounds like a problem with one of the addons.

**Comment by Miedzcu** [comment]
> Actually, I haven’t figured it out other than it is not the script, but my Firefox. Every other browser it works just fine. Actually, it works fine in Private browsing in Firefox, but not the regular browser. I will continue to troubleshoot.Thanks for the response and a cool script.

Clear cookies in regular browser.

**Comment by dgronos** [comment]
Problem solved.  Cookies and cache cleared loads with no problem now.
