### ISSUE TITLE
Compatibility for Debian 12 Bookworm

### ISSUE THREAD

**Issue by thatandrewguy** [Bercik1337/rt-auto-install#47]
Hi there,

Are you able to please make this script compatible with Debian 12 Bookworm?

**Comment by Bercik1337** [comment]
@thatandrewguy sure, but probably weekend 2 weeks from now. very busy :(

**Comment by Bercik1337** [comment]
@thatandrewguy done

**Comment by thatandrewguy** [comment]
> @thatandrewguy done

Thank you!
