### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by 4w3e** [Bercik1337/rt-auto-install#5]
Cześć, można się z Tobą jakoś skontaktować przez maila lub gg? Jestem zielony w tych sprawach a mam kilka pytań :)

**Comment by Bercik1337** [comment]
Pisz tu.

**Comment by 4w3e** [comment]
![fail](https://user-images.githubusercontent.com/59577343/72726965-fe3a1880-3b89-11ea-9f10-e6b311a1e0e6.png)

Takie coś mi wyskakuje ;(

**Comment by Bercik1337** [comment]
To nie wygląda jak świeża instalka systemu. Przeznaczenie jest aby to robić na czystym systemie bo takto nie wiadomo co kto grzebał i potem sie trzeba dwoić i troić o co chodzi.
Na szybko to pokaż 
`cat /var/log/dpkg.log`

zrób też 
```
sudo dpkg --configure –a
sudo apt-get install –f
```

a najlepiej to to po prostu zainstaluj na czystym systemie i się nie męcz.

**Comment by 4w3e** [comment]
To jest postawione na VPS od hostsolutions.ro
W panelu serwera mam następujące systemy do zainstalowania:
centos7img |  centos8img |  debian10img |  ubuntu18img |  ubuntu1910img

później, spróbuję jeszcze raz postawić system, na nowo.
A wygląda to tak ponieważ łączę się przez ich VNCconsole, bo przez putty nie mogę się połączyć ;(

Jeszcze takie pytanie:
Podczas instalacji skrypt pyta o użytkownika, ten użytkownik musi mieć uprawnienia "administratora" czy tam sudo?  pytam bo wszystko robię na konice root

**Comment by Bercik1337** [comment]
Podczas kreatora jest napisane, że musisz to uruchomić z uprawnieniami admina (sudo lub jako root, obojętne) ale **należy podać konto lokalne tak aby rtorrent mógł chodzić na owym koncie**. Musisz mieć jednego zwykłego użytkownika na systemie.

**Comment by 4w3e** [comment]
Po "postawieniu' nowego Ubuntu 18.04 wszystko ładnie przeszło :) 
Tylko po przekopiowaniu ip rutorrent do przeglądarki, pyta mnie dane do logowania, próbowałem wszystkie możliwości pw użytkownika, którego stworzyłem, pw roota i nic, nie wiesz gdzie może być problem?
![pww](https://user-images.githubusercontent.com/59577343/72751626-64da2900-3bc0-11ea-8c7d-8350522187f7.jpg)

**Comment by Bercik1337** [comment]
podczas instalacji podajesz 1. nazwe kontalokalnego 2. login to rutorrenta, 3. hasło do rutorrenta, w tym oknie musisz podać te z punktu 2 i 3

**Comment by 4w3e** [comment]
ok, jutro postawię jeszcze raz wszystko na nowo ;) dzięki wielkie za pomoc!!
