### ISSUE TITLE
Rutorrent unable to connect to rtorrent

### ISSUE THREAD

**Issue by huttsMichael** [Bercik1337/rt-auto-install#50]
Hello, I ran your script and it was all relatively smooth but for whatever reason rutorrent isn't able to connect to rtorrent. I've confirmed both are running with no errors beyond rutorrent being unable to connect to rtorrent.  I'm running Debian 11 (OpenMediaVault to be precise) by the way. 

Here's the exact rutorrent log:
```
[03.08.2023 16:32:53] WebUI started.
[03.08.2023 16:32:54] No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file.
[03.08.2023 16:32:54] _cloudflare: Plugin will not work. Webserver user can't access external program (python).
```

Just as a sanity check to the solution described in the error,  here's the port settings:

config.php:
```
        $scgi_port = 5000;
        $scgi_host = "127.0.0.1";
```

 .rtorrent.rc:
```
scgi_port = 127.0.0.1:5000
```

I think that's all the relevant info I can offer but let me know if there's anything else I can offer to help diagnose what went wrong here.

**Comment by huttsMichael** [comment]
I figured it out, it's a bit obvious looking at the logs I sent, though the fact that rtorrent was still running fine made it a bit unclear. I installed the python package and it's now connecting fine with rtorrent, although I still confusingly have the following errors now:
```
[03.08.2023 17:26:28] WebUI started.
[03.08.2023 17:26:29] spectrogram: Plugin will not work. rTorrent user can't access external program (sox).
[03.08.2023 17:26:29] screenshots: Plugin will not work. rTorrent user can't access external program (ffmpeg).
[03.08.2023 17:26:30] _cloudflare plugin: cloudscraper module can't be loaded in Python
```

**Comment by Bercik1337** [comment]
@huttsMichael I didn't test it on open media vault. My test path always covers "clean" install of supported OS.
Please ignore missing spectrogram/screenshots/_cloudflare  - it's not a bug. I just don't don't want them to install because they are huge on diskspace and give me nothing. 
You can mark them as disablled or apt install missing programs.

I think I'll add a message about this in the installation screen because numerous people come in here asking about them, yet they didn't even check that rtorrent works fine without them.

**Comment by huttsMichael** [comment]
As far as OpenMediaVault support, everything else works fine once python is installed manually, so if python was added to an apt install call during setup, OpenMediaVault 6 could be listed as a fully supported distro. Understandable if you want to avoid adding less "mainline" distros and any future maintenance that'd entail, but at the moment it seems to be pretty simple ordeal. I was expecting issues with its built-in dashboard since it's using the same service but rutorrent coexists with OMV just fine thankfully. 
Regardless, thanks for your work on the script that it works so smooth on something you hadn't even targeted for compatibility :)

**Comment by Bercik1337** [comment]
I'll try to experiment with python, but $20 it's under different names for different distros. :(
If we're lucky, this weekend could be a timeslot for me.

Unless you want to help out with testing and so on. :crossed_fingers:

**Comment by huttsMichael** [comment]
Hi @Bercik1337 my apologies I missed this response. I couldn't do a test on the original system I encountered the issue at the moment, but I could test on a VM if you'd like

**Comment by Bercik1337** [comment]
if you can, go ahead. i can't test this weekend (also next one)

**Comment by 7h3Cub3** [comment]
> I figured it out, it's a bit obvious looking at the logs I sent, though the fact that rtorrent was still running fine made it a bit unclear. I installed the python package and it's now connecting fine with rtorrent, although I still confusingly have the following errors now:
> 
> ```
> [03.08.2023 17:26:28] WebUI started.
> [03.08.2023 17:26:29] spectrogram: Plugin will not work. rTorrent user can't access external program (sox).
> [03.08.2023 17:26:29] screenshots: Plugin will not work. rTorrent user can't access external program (ffmpeg).
> [03.08.2023 17:26:30] _cloudflare plugin: cloudscraper module can't be loaded in Python
> ```
> 
> Edit: installed the two other missing dependencies so that's resolved, but I'm still getting the python error. just for reference:
> 
> ```
> rt@openmediavault:~$ which python
> /usr/bin/python
> rt@openmediavault:~$ which python3
> /usr/bin/python3
> ```
> 
> My main problem is fixed at this point but I won't close it yet incase anyone might have a clue what's going on with this plugin

Hello, had the same issue, fixed it by adding a symlink ln -s /usr/bin/python3 /usr/bin/python you can also tweak in your rutorrent install folder plugins/_cloudflare/conf.php the python path and or name it must be looking for.

Cheers.

**Comment by Bercik1337** [comment]
Hey buddy,
I think I'll add info after installation so people can IGNORE these warnings, or if they really want to - just apt install these packages. 
They are NOT essential for rutorrent to work, and I decided not to install them because they take a lot of space on HDD.

Hopefully it's going to be done with newest update (maybe this weekend 🤞 )
