### ISSUE TITLE
rtorrent-Rutorrent

### ISSUE THREAD

**Issue by GitHub-BumBleBee** [Bercik1337/rt-auto-install#53]
I'm Diego from Brazil and I'm new to Ubuntu 22.04.03 LTS. I would like to pay someone who can install Rtorrent-Rutorrent. I will pass remote access through teamviewer.

**Comment by Bercik1337** [comment]
I could do this for $100 but if you can't install it yourself, are you sure you'll know how to use it later?

**Comment by GitHub-BumBleBee** [comment]
Using the client would just turn on the PC and open the client and add torrents to it, right?


Hello, I would film the procedure with my cell phone, and I would ask you to put the procedures used in 1 .txt.


How would I pay you?

**Comment by Bercik1337** [comment]
it depends - do you have Ubuntu installed on your computer, or you using seedbox/remote server?

I can invoice you, regular wire transfer would do. We can do 50% before and 50% after service. I would give you BIC/SWIFT and account number. Just ask your bank if you need anything more.

What timezone are you in?

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 
I am from Brazil.
A friend made it and I paid for it. But thank you very much for your attention. Thank you

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 

Friend I am very grateful for your services, can I make a donation to you?

**Comment by Bercik1337** [comment]
@GitHub-BumBleBee  bom dia. I think yes, do you have a Revolut account?

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 Here we only have PayPal Bank

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 Buddy, you didn't talk to me anymore. It's not going to work?

**Comment by Bercik1337** [comment]
@GitHub-BumBleBee sorry i was (and still am) very busy.
I don't have Paypal anymore because i hate this company. If you can't do wire transfer to account number, then I think i'm out of options. :( 
but thanks for trying to give me money. muito obrigado

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 I have to thank you for doing a very good job, congratulations. And thank you.

If you ever need help in any way, I'll be here, just ask. I really liked you and I want to always be at your disposal.

**Comment by Bercik1337** [comment]
my pleasure.
Closing issue.
