### ISSUE TITLE
Rtorrent-RuTorrent

### ISSUE THREAD

**Issue by GitHub-BumBleBee** [Bercik1337/rt-auto-install#54]
@Bercik1337 

Hello, I really need your help. I had to install Linux Mint 21 on my notebook, because only it recognized 1 NVMe of 4TB. Before I used Ubuntu and didn't have this problem. My Rutorrent is not opening port. It is already released on the router. Help. I know you're very busy. I pay for the service, but please help me.

https://i.postimg.cc/cJgpYLcx/Captura-de-tela-de-2023-09-07-17-18-13.png

**Comment by Bercik1337** [comment]
paste `grep -i port ~/.rtorrent.rc`     and `ip a` and portforward config from your router.
I'm going to bed, so i'll check it tomorrow

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 

I'm sending you 1 Rutorrent configuration file link. My local IP is 10.0.0.150. The other IP changes directly. If you have time I open a remote access for you.

The other ports are working 100%.

https://drive.google.com/drive/folders/1IKyJEu3Gf6Bo85nsSPbXs-8OB8KUXVzW?usp=sharing

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 


Hello friend. Did you see anything wrong?

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 

Friend, I changed the port to 21000 and 23000 and it worked. Thanks again for your attention. And sorry to bother you!!

**Comment by Bercik1337** [comment]
Just noticed your posts. I'm glad it worked fine. 
Happy seeding
