### ISSUE TITLE
How do I show the correct Disk Size?

### ISSUE THREAD

**Issue by iNanja** [Bercik1337/rt-auto-install#55]
![temp](https://github.com/Bercik1337/rt-auto-install/assets/18370211/ec461127-75e8-431e-b032-4a9542228598)

I can't figure out how to show the correct disk size on home, right now it shows 502GB at the very bottom left.

What I have mounted using df -H says

> /dev/md3         30T   95k   28T   1% /home

How do I fix this?

**Comment by Bercik1337** [comment]
```
18:55:53-bercik@pollux:/var/www/rutorrent/plugins/diskspace$ cat conf.php
<?php

$diskUpdateInterval = 10;       // in seconds
$notifySpaceLimit = 512;        // in Mb
$partitionDirectory = null;     // if null, then we will check rtorrent download directory (or $topDirectory if rtorrent is unavailable)
                                // otherwise, set this to the absolute path for checked partition.

```
So just modify in `~/.rtorrent.rc`

this line
# Default directory to save the downloaded torrents.
directory = /home/yourdestinationfolder
