### ISSUE TITLE
update rutorrent to 4.2.6

### ISSUE THREAD

**Issue by TMTYD** [Bercik1337/rt-auto-install#56]
Hi

How can I update rutorrent to the latest version 4.2.6 of Novik?

**Comment by Bercik1337** [comment]
just download newest rutorrent from internet and unzip it's content to /var/www/rutorrent
when i have some free time - i'll update this package in my script (but not soon)

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 


Hello, a question.. What do I do when you make changes to Script. What would the update process be like in Linux Mint 21?

**Comment by Bercik1337** [comment]
I don't understand your question. We currently support Mint 21.
When I change rutorrent version, it changes for ALL supported systems.

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 
I'm from Brazil, I use a translator.

Friend.. My doubt would be. How will I apply your update?
In an already installed script?

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 

What options would I have, how do I do them?

**Comment by Bercik1337** [comment]
in theory you could re-run the script. but i highly recommend to setup fresh  system. this way you won't brake anything.

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337     Please read everything, there are many questions!


Friend, I'm not going to set up a new system. Every time you make a new update to the script. This suggestion is disregarded. Even because I have 3TB of files.


One question... The most important thing would be to have the rutorrent version updated???


Is there a file that I can edit the version of. Example: Today there is v4.1.6 where I open it. Show me this version. Can I edit this version?


I'm thinking about just updating utorrent, can I?

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 When you have time, answer my various questions, please!

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 Sorry to bother you so much, but I need your help!


I'm in doubt. If there is any file that I can edit the version of rutorrent?

Today it is at v4.1.6, I can edit this version

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 

What I want to change is circled in red.


https://i.postimg.cc/kgmVdkYW/Captura-de-tela-2023-09-16-044015.png

**Comment by Bercik1337** [comment]
To edit this name just right-click on bookmark and select "edit bookmark". You can rename it to anything you want.

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 

There is some file inside the installation. That I can edit through the terminal?

What is the file name and location?

**Comment by GitHub-BumBleBee** [comment]
@Bercik1337 I'm very organized...

Is there a file that is a reference. That has the rutorrent version. It's great for me to change, always. It helps me...

**Comment by Bercik1337** [comment]
finally upgrade is coming up in just a moment
