### ISSUE TITLE
Possible changes?

### ISSUE THREAD

**Issue by skl283** [Bercik1337/rt-auto-install#6]
Hey Bercik,

nice Script! Work very good! I have a question - is it possible to add/change support for:

- newest rTorrent (0.9.8) in Script is 0.9.7
- newest rutorrent (--> latest GIT-Version?)
- NGINX instead of apache

sash

**Comment by Bercik1337** [comment]
@skl283 
Hey, sorry for late response:

    newest rTorrent (0.9.8) in Script is 0.9.7
This one is based on repository. So the moment newer version shows up, it will use it.

    newest rutorrent (--> latest GIT-Version?)
I'll take a look at it when I have some spare time. Hopefully it will work without problems. If I don't publish within 2 weeks you could ping me.

    NGINX instead of apache
In long long future yes, but I don't have time for it. This script is for people who don't know how to setup rT + ruT. If someone needs NGINX for whatever reason, they can setup themselves.

Of course if you or anyone will make a change and I'll test it - there is no problem for me to accept pull request.

**Comment by Bercik1337** [comment]
@skl283 I added version 0.9.8 because it's available in repo for modern systems, see section: case $OSFINALNAME in (line 118) for details. Ubuntu 20.04 and Debian buster have newest rtorrent possible.

**Comment by greg811** [comment]
I also have request to update rutorrent. Wersion 3.7 is quite old release.

**Comment by Bercik1337** [comment]
I see we even have 3.10 now. Gonna update it with next release.
