### ISSUE TITLE
Debian 12 issues

### ISSUE THREAD

**Issue by Miedzcu** [Bercik1337/rt-auto-install#61]
Po wykryciu Debiana 12 poniższe komendy: 
```
chown "$RTORRENT_USER"."$RTORRENT_GROUP" "$HOMEDIR"/.rtorrent-session
chown "$RTORRENT_USER"."$RTORRENT_GROUP" "$HOMEDIR"/Downloads
chown "$RTORRENT_USER"."$RTORRENT_GROUP" $HOMEDIR/.rtorrent.rc
chown -R www-data.www-data /var/www/
```

Nie działają - właściwy system domaga się zapisu (możliwe, wybór jest wybór języka systemu ten u mnie to PL):

```
chown "$RTORRENT_USER":"$RTORRENT_GROUP" "$HOMEDIR"/.rtorrent-session
chown "$RTORRENT_USER":"$RTORRENT_GROUP" "$HOMEDIR"/Downloads
chown "$RTORRENT_USER":"$RTORRENT_GROUP" $HOMEDIR/.rtorrent.rc
chown -R www-data:www-data /var/www/
```

Oczywiście problem można bardzo łatwo naprawić we własnym zakresie. Zgłaszam jedynie by najmniej osób spotykało ten problem w przyszłości co powinno pomoc przy propagacji skryptu.

**Comment by Bercik1337** [comment]
Obczaje w wolnej chwili

**Comment by Bercik1337** [comment]
@Miedzcu  podaj jakiego dokładnie ISO użyłeś, bo mi na debian livecd 12 xfce przeszło bez problemu.

**Comment by Miedzcu** [comment]
> @Miedzcu podaj jakiego dokładnie ISO użyłeś, bo mi na debian livecd 12 xfce przeszło bez problemu.

ISO netinst dla 64-bitowego PC (https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.4.0-amd64-netinst.iso)

Nie wiem czy polska wersja językowa bądź też wybór PL-PL dla klawiatury nie powoduje tego problemu.

**Comment by Bercik1337** [comment]
@Miedzcu poszło mi na tym konkretnym ISO za równo dla ang/us jak i polska/pl

Opluł tylko warningiem dla `chown` ale wszystko działa poprawnie.

**Comment by Bercik1337** [comment]
Możesz wkleić np pełnego loga  ze wszystkich komunikatów? Bo jeśli na tym konkrentym iso mi działa dobrze, to wręcz niemożliwe aby gdzieś nie działało.

**Comment by Miedzcu** [comment]
> Opluł tylko warningiem dla `chown` ale wszystko działa poprawnie.

O właśnie o tym mówię (żebym dobrze był zrozumiany to oplucie to jedyny problem). 

Instalator nie przerywa pracy kontynuuje a efekt jest ostatecznie zainstalowana całości- trzeba jedynie manualnie dodać uprawnienia do modyfikacji zawartości folderów (co najmniej  /Downloads). Inaczej dodany plik torrent nie wystartuje (będzie wiecznie za'pausowany na 0%).
