### ISSUE TITLE
Fresh install on Ubuntu 22.04, rtorrent refuses to start

### ISSUE THREAD

**Issue by chapit-nicolas** [Bercik1337/rt-auto-install#62]
Hi, 

I tried 2 times today to install it on my server. The installation ends correctly, but the rtorrent.service refuses to start.

From syslog:

1. Dec 19 20:51:16 ns329804 systemd[1]: rtorrent.service: Scheduled restart job, restart counter is at 46.
2. Dec 19 20:51:16 ns329804 systemd[1]: Stopped rtorrent (in tmux).
3. Dec 19 20:51:16 ns329804 systemd[1]: Starting rtorrent (in tmux)...
4. Dec 19 20:51:16 ns329804 systemd[1]: Started rtorrent (in tmux).
5. Dec 19 20:51:16 ns329804 tmux[3188]: no server running on /tmp/tmux-1002/default
6. Dec 19 20:51:16 ns329804 systemd[1]: rtorrent.service: Control process exited, code=exited, status=1/FAILURE
7. Dec 19 20:51:16 ns329804 systemd[1]: rtorrent.service: Failed with result 'exit-code'.

I had to install sox and ffmpeg. Python was already there at v3.10.

Any idea why?
If you need more log(s), let me know.

Thanks in advance.

**Comment by chapit-nicolas** [comment]
For some weird reason, after an upgrade (libssh-4 libssh-gcrypt-4 openssh-client openssh-server openssh-sftp-server) and a reboot, it seems to start normally 🤔 

I did reboots before opening this issue, and it was always the same problem...

Good to close, unless you have some addition?

**Comment by Bercik1337** [comment]
@chapit-nicolas sorry i just noticed this issue. Don't know why github doesn't notify me.

did you try this on a fresh install? i have just recently rerun installer for Debian 12 and Ubuntu for someone else's issue and there were no problems. So i doubt it's global problem for all installs.
Unless you want to rerun the install in another VM or something ( i can gladly help) to reproduce this bug.  Alternatively we can close it.

**Comment by chapit-nicolas** [comment]
@Bercik1337 No worries, it's holiday season, we have many others stuff to handle ;)

Currently, this was my plan to pop a VM. I will tell you more when it will be done.

**Comment by chapit-nicolas** [comment]
So I just finished to setup the VM, and everything is ok, even the others problem I have with my main server (Rtorrent User can execute external program php, python...) But this one has nothing to see with our current issue.

Thanks.

Good to close.
