### ISSUE TITLE
How to mount an older hard disk with a .session and a corresponding downloads directories to resume?

### ISSUE THREAD

**Issue by rjalexa** [Bercik1337/rt-auto-install#63]
A power failure fried my Raspberry MicroSD and I am reinstalling a Debian 12 light and am looking at your script with GREAT interest.

Do you know in which way I could mount or copy the files from the directories on the external HDD to resume my previous torrents?

In the .sessions directory I see two files with an HASHVALUE.torrent.rtorrent and HASHVALUE.torrent.

In the former I can still see the old mountpoint of the torrent:

`directory82:/home/bob/torrents/rtorrent/Debian-12-micro.iso`

and in the downloads directory I have the files of the torrent.

Any hope ? Thank you

**Comment by Bercik1337** [comment]
Hey
Just make sure after you move session directory, the .rtorrent.rc should point to that location.
You can easily find how to do this online because it's not related to my script, it's generic rtorrent question.
