### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by rjalexa** [Bercik1337/rt-auto-install#64]
Thank you for your work.

Installing on Debian 12 for RPi fails.

A couple of syntax warnings about chown wanting user:user and not user.user:
```
[ok]
Creating session directory 
chown: warning: '.' should be ':': ‘bob.1000’
[ok]
Creating Downloads directory 
chown: warning: '.' should be ':': ‘bob.1000’
[ok]
```
but more importantly: (I HAVE REPLIED FOR THIS IN THE ISSUE ABOUT ARM) thanks
```
Download scgi
--2024-01-18 09:35:15--  http://mirrors.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb
Resolving mirrors.kernel.org (mirrors.kernel.org)... 139.178.88.99, 2604:1380:45e3:2400::1
Connecting to mirrors.kernel.org (mirrors.kernel.org)|139.178.88.99|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://mirrors.edge.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb [following]
--2024-01-18 09:35:15--  http://mirrors.edge.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 147.75.80.249, 2604:1380:4601:e00::3
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|147.75.80.249|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12020 (12K) [application/octet-stream]
Saving to: ‘libapache2-mod-scgi_1.13-1.1build1_amd64.deb’

libapache2-mod-scgi_1.13-1.1build1_amd64.deb      100%[==========================================================================================================>]  11.74K  --.-KB/s    in 0s      

2024-01-18 09:35:15 (48.6 MB/s) - ‘libapache2-mod-scgi_1.13-1.1build1_amd64.deb’ saved [12020/12020]

Install scgi
dpkg: error processing archive libapache2-mod-scgi_1.13-1.1build1_amd64.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 libapache2-mod-scgi_1.13-1.1build1_amd64.deb
[FAIL]
```
as you can see the problem lies in the fact that it is trying to install an AMD64 version of the scgi package and not the ARM64 it should as that's the architecture of the Raspberry 4.

Thank you

**Comment by Bercik1337** [comment]
Yes, ARM support is broken now, because I have old raspberry and I can't test on new hardware (it's different architecture).
SCGI package is for amd64 instead of arm because I can't differentiate between old and new RPIs.

When i found some time I'll exclude support for RPI so it won't confuse more people.

**Comment by filmaidykai** [comment]
Creating session directory 
chown: warning: '.' should be ':': ‘pi.1000’
[ok]
Creating Downloads directory 
chown: warning: '.' should be ':': ‘pi.1000’
[ok]
Copying rtorrent.rc
[ok]
chown: warning: '.' should be ':': ‘pi.1000’
Download scgi
--2024-02-11 14:10:25--  http://mirrors.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb
Resolving mirrors.kernel.org (mirrors.kernel.org)... 2604:1380:45e3:2400::1, 139.178.88.99
Connecting to mirrors.kernel.org (mirrors.kernel.org)|2604:1380:45e3:2400::1|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://mirrors.edge.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb [following]
--2024-02-11 14:10:25--  http://mirrors.edge.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 2604:1380:4601:e00::3, 147.75.80.249
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|2604:1380:4601:e00::3|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12020 (12K) [application/octet-stream]
Saving to: ‘libapache2-mod-scgi_1.13-1.1build1_amd64.deb’

libapache2-mod-scgi 100%[===================>]  11.74K  --.-KB/s    in 0s      

2024-02-11 14:10:25 (51.8 MB/s) - ‘libapache2-mod-scgi_1.13-1.1build1_amd64.deb’ saved [12020/12020]

Install scgi
dpkg: error processing archive libapache2-mod-scgi_1.13-1.1build1_amd64.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 libapache2-mod-scgi_1.13-1.1build1_amd64.deb
[FAIL]

**Comment by Bercik1337** [comment]
yes it's the same problem
