### ISSUE TITLE
Multi user with separate downloads folders

### ISSUE THREAD

**Issue by unk972** [Bercik1337/rt-auto-install#67]
Hello,

Do you have a solution to use multiple users with different download folders?
Because when I create two users they have access to the same download folder. And same rutorrent...

Thanks

**Comment by Bercik1337** [comment]
Hi, I have never used multi-user setup. Honestly i don't think i'll sit on it quickly (lack of time).
I'll leave it open, perhaps someone can help out sooner or i'll come back here in few weeks.
Sorry very busy

try to google apache2 rutorrent multi user setup
