### ISSUE TITLE
Typo in '# Copying rtorrent.rc file.' sections

### ISSUE THREAD

**Issue by Aergernis** [Bercik1337/rt-auto-install#68]
Hi,

there's a typo in all `# Copying rtorrent.rc file.` sections. It should be `:` instead of `.`

**Comment by Bercik1337** [comment]
Hi
Honestly i'm not sure what you mean. Could you submit PR or at least paste here example `before` and `after` line? Thx

**Comment by AndyC52** [comment]
It's on line 441 and others:
`chown "$RTORRENT_USER"."$RTORRENT_GROUP" $HOMEDIR/.rtorrent.rc`

**Comment by Bercik1337** [comment]
`chown` supports both syntaxes. I just checked myself manually and it works fine.

Do you receive any error message? If so - please paste it here.
