### ISSUE TITLE
Failed to stop rtorrent-init.service: Unit rtorrent-init.service not found.

### ISSUE THREAD

**Issue by Impact009** [Bercik1337/rt-auto-install#69]
`sudo service rtorrent-init start
Failed to start rtorrent-init.service: Unit rtorrent-init.service not found.

sudo service rtorrent-init stop
Failed to stop rtorrent-init.service: Unit rtorrent-init.service not loaded.`

rtorrent auto-starts every time I boot, so the service seems to be working. It's just weird that the service can't be found. I have reformatted and performed a clean installation of Debian 12 (Bookform (64bits) three times. Where is the log from the installation? I didn't see a relevant log within the script's code.

This seems to be the same issue as #21.

**Comment by MarkusLange** [comment]
The service is called rtorrent.service not rtorrent-init.service

**Comment by Impact009** [comment]
Thanks. The documentation is outdated and should be updated.

`Use "service rtorrent-init start" and "service rtorrent-init stop" to start and stop rtorrent respectively.`

**Comment by Bercik1337** [comment]
@MarkusLange @Impact009  thx guys, updated README coming right up. I finally found 5min.
