### ISSUE TITLE
Dowload don't start

### ISSUE THREAD

**Issue by Norbi86k86** [Bercik1337/rt-auto-install#71]
The installation went without a problem. But when I add .torrent files via webappi they do not download. Additionally, after editing the .rtorrent.rc file and adding the WATCH directory, rutorrent does not search for this directory itself.
Please advise what could be the cause.
I installed on Debian 12. Clean installation.
![foto](https://github.com/user-attachments/assets/a96dd875-6cb2-44a4-8034-73f830fb4a95)

**Comment by Bercik1337** [comment]
@Norbi86k86 what happens if you manually stop and then start these torrents using buttons on top?
