### ISSUE TITLE
debian 10 and rtorrent/rutorrent issues

### ISSUE THREAD

**Issue by luckypackets** [Bercik1337/rt-auto-install#8]
on debian 10, if rutorrent shows the error "No connection to rTorrent. Check if it is really running. Check $scgi_port and $scgi_host settings in config.php and scgi_port in rTorrent configuration file" or rtorrent shows the error "rtorrent: Could not open/bind port for listening: Address family not supported by protocol", a solution that seems to be working (for me so far at least) is to add:
bind = 0.0.0.0
to the .rtorrent.rc file under the line scgi_port = 127.0.0.1:5000

the error(s) show if ipv6 is disabled or not available on debian 10. might be something you'd want to add to the script?

**Comment by Bercik1337** [comment]
@luckypackets hey, I just noticed this post. I will check it out after the weekend, because last time i tried it was working just fine under Debian10.
If it happens, then I'll update this config.
Have you tried this on many systems or just this one?

**Comment by Bercik1337** [comment]
@luckypackets I just checked quickly on VM for debian-10.6.0-amd64-netinst.iso  and there was absolutely no problem installing and running it. Do you use fresh installation?

**Comment by luckypackets** [comment]
@Bercik1337 oh, hmmm. i did, let me try it again on a new vm using 10.6.0, hadn't come out yet so I was using 10.5.0, maybe something was fixed/changed in 10.6 :)

**Comment by Bercik1337** [comment]
@luckypackets I didn't change anything ;P remember everything must be used on fresh install of OS. If anything is tampered with, it can cause problems.
